In [1]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
# print(f"API Key: {api_key}")

client = OpenAI()

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)

In [2]:
print(completion.choices[0].message)

ChatCompletionMessage(content="In the realm of code, there lies a method divine,\nA looping dance that's elegant and oh so fine.\nRecursion, the art of self-calling grace,\nA technique that brings a smile to a programmer's face.\n\nLike a mirror reflecting its own image clear,\nRecursion calls itself, with no trace of fear.\nBreaking big problems into smaller bites,\nIt conquers complexity with dazzling lights.\n\nA function that calls itself, again and again,\nSolving puzzles with a recursive refrain.\nEach call delving deeper into the maze,\nUntil the goal is found, in a mesmerizing blaze.\n\nBut beware the infinite loop's cruel snare,\nCareful design is key, handle with care.\nBase cases like anchors in a stormy sea,\nGuide recursion safely, setting the code free.\n\nSo embrace this concept, let it be your friend,\nRecursion's power is yours to transcend.\nUnlocking mysteries, with each recursive call,\nIn the wondrous world of code, you'll stand tall.", role='assistant', function_call=None, tool_calls=None)

In [3]:
print(completion.choices[0].message.content)

In the realm of code, there lies a method divine,
A looping dance that's elegant and oh so fine.
Recursion, the art of self-calling grace,
A technique that brings a smile to a programmer's face.

Like a mirror reflecting its own image clear,
Recursion calls itself, with no trace of fear.
Breaking big problems into smaller bites,
It conquers complexity with dazzling lights.

A function that calls itself, again and again,
Solving puzzles with a recursive refrain.
Each call delving deeper into the maze,
Until the goal is found, in a mesmerizing blaze.

But beware the infinite loop's cruel snare,
Careful design is key, handle with care.
Base cases like anchors in a stormy sea,
Guide recursion safely, setting the code free.

So embrace this concept, let it be your friend,
Recursion's power is yours to transcend.
Unlocking mysteries, with each recursive call,
In the wondrous world of code, you'll stand tall.

### READ DATASET FROM HUGGINGFACE

In [2]:
from datasets import load_dataset
import pandas as pd

/home/yasser/Documents/pa/.pa/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = load_dataset("gretelai/synthetic_text_to_sql", split='train')

In [4]:
df

Dataset({
    features: ['id', 'domain', 'domain_description', 'sql_complexity', 'sql_complexity_description', 'sql_task_type', 'sql_task_type_description', 'sql_prompt', 'sql_context', 'sql', 'sql_explanation'],
    num_rows: 100000
})

In [8]:
type(df)

datasets.arrow_dataset.Dataset

In [5]:
df[0]

{'id': 5097,
 'domain': 'forestry',
 'domain_description': 'Comprehensive data on sustainable forest management, timber production, wildlife habitat, and carbon sequestration in forestry.',
 'sql_complexity': 'single join',
 'sql_complexity_description': 'only one join (specify inner, outer, cross)',
 'sql_task_type': 'analytics and reporting',
 'sql_task_type_description': 'generating reports, dashboards, and analytical insights',
 'sql_prompt': 'What is the total volume of timber sold by each salesperson, sorted by salesperson?',
 'sql_context': "CREATE TABLE salesperson (salesperson_id INT, name TEXT, region TEXT); INSERT INTO salesperson (salesperson_id, name, region) VALUES (1, 'John Doe', 'North'), (2, 'Jane Smith', 'South'); CREATE TABLE timber_sales (sales_id INT, salesperson_id INT, volume REAL, sale_date DATE); INSERT INTO timber_sales (sales_id, salesperson_id, volume, sale_date) VALUES (1, 1, 120, '2021-01-01'), (2, 1, 150, '2021-02-01'), (3, 2, 180, '2021-01-01');",
 'sql': 'SELECT salesperson_id, name, SUM(volume) as total_volume FROM timber_sales JOIN salesperson ON timber_sales.salesperson_id = salesperson.salesperson_id GROUP BY salesperson_id, name ORDER BY total_volume DESC;',
 'sql_explanation': 'Joins timber_sales and salesperson tables, groups sales by salesperson, calculates total volume sold by each salesperson, and orders the results by total volume in descending order.'}

## FORMAT THE DATA

In [ ]:
df = df.to_pandas()

In [35]:
df = df[['sql_prompt', 'sql']][:1000]
df

,sql_prompt,sql
0,What is the total volume of timber sold by eac...,"SELECT salesperson_id, name, SUM(volume) as to..."
1,List all the unique equipment types and their ...,"SELECT equipment_type, SUM(maintenance_frequen..."
2,How many marine species are found in the South...,SELECT COUNT(*) FROM marine_species WHERE loca...
3,What is the total trade value and average pric...,"SELECT trader_id, stock, SUM(price * quantity)..."
4,Find the energy efficiency upgrades with the h...,"SELECT type, cost FROM (SELECT type, cost, ROW..."
...,...,...
995,What is the total funding received by companie...,"SELECT company_id, SUM(amount) as total_fundin..."
996,How many publications were made by graduate st...,SELECT COUNT(Publications) FROM GraduateStuden...
997,Which space agencies have launched spacecraft ...,SELECT DISTINCT agency FROM spacecraft WHERE Y...
998,What's the total amount of climate finance com...,SELECT SUM(amount) FROM climate_finance WHERE ...
999,What is the total value of investments in bond...,SELECT SUM(Value) FROM ClientInvestments CI JO...

In [67]:
def convert_to_gpt35_format(dataset):
    fine_tuning_data = []
    for _, row in dataset.iterrows():
        fine_tuning_data.append({
            "messages": [
                {"role": "user", "content": row['sql_prompt']},
                {"role": "assistant", "content": row['sql']},
            ]
        })
    return fine_tuning_data

In [68]:
converted_data = convert_to_gpt35_format(df)

In [70]:
converted_data[0]

{'messages': [{'role': 'user',
   'content': 'What is the total volume of timber sold by each salesperson, sorted by salesperson?'},
  {'role': 'assistant',
   'content': 'SELECT salesperson_id, name, SUM(volume) as total_volume FROM timber_sales JOIN salesperson ON timber_sales.salesperson_id = salesperson.salesperson_id GROUP BY salesperson_id, name ORDER BY total_volume DESC;'}]}

## Creating Training and Validation Sets

In [71]:
from sklearn.model_selection import train_test_split

# Stratified splitting. Assuming 'Top Category' can be used for stratification
train_data, val_data = train_test_split(
    converted_data,
    test_size=0.2,
    random_state=42  # for reproducibility
)

In [72]:
train_data

[{'messages': [{'role': 'user',
    'content': 'How many companies were founded by women in the San Francisco Bay Area?'},
   {'role': 'assistant',
    'content': "SELECT COUNT(*) FROM companies WHERE city='San Francisco' AND state='CA' AND founder_gender='female';"}]},
 {'messages': [{'role': 'user',
    'content': 'List all chemical batches with a pH level above 9, produced in the USA since January 2021, along with their production dates.'},
   {'role': 'assistant',
    'content': "SELECT id, pH, production_date FROM ChemicalBatches WHERE pH > 9 AND production_date >= '2021-01-01';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the minimum ocean acidification level recorded in the Pacific Ocean, and which research station had this level?'},
   {'role': 'assistant',
    'content': "SELECT research_station.station_name, oa.level AS min_level FROM ocean_acidification oa JOIN (SELECT location, MIN(level) AS min_level FROM ocean_acidification WHERE region = 'Pacific Ocean' GROUP BY location) oa_min ON oa.level = oa_min.min_level JOIN research_stations research_station ON oa.location = research_station.station_name;"}]},
 {'messages': [{'role': 'user',
    'content': "Who funded the excavation of 'Palenque' and what was the date?"},
   {'role': 'assistant',
    'content': "SELECT FundingAgency, FundingDate FROM Funding f JOIN ExcavationSites e ON f.SiteID = e.SiteID WHERE e.SiteName = 'Palenque';"}]},
 {'messages': [{'role': 'user',
    'content': 'Which climate adaptation projects were completed in Southeast Asia in 2017 and what was their combined cost?'},
   {'role': 'assistant',
    'content': "SELECT region, SUM(cost) FROM climate_adaptation WHERE year = 2017 AND region = 'Southeast Asia' GROUP BY region;"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the distribution of employee tenure by job level, manager, and ethnicity?'},
   {'role': 'assistant',
    'content': 'SELECT Employees.JobLevel, Employees.Manager, Employees.Ethnicity, AVG(Employees.Tenure) as Avg_Tenure FROM Employees GROUP BY Employees.JobLevel, Employees.Manager, Employees.Ethnicity;'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the total donation amount for each gender?'},
   {'role': 'assistant',
    'content': 'SELECT Gender, SUM(DonationAmount) FROM Donors GROUP BY Gender;'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average caloric content of organic products sold by retailers in the Northeast region?'},
   {'role': 'assistant',
    'content': "SELECT AVG(inventory.caloric_content) FROM inventory JOIN products ON inventory.product_id = products.product_id JOIN retailers ON inventory.retailer_id = retailers.retailer_id WHERE products.is_organic = TRUE AND retailers.region = 'Northeast';"}]},
 {'messages': [{'role': 'user',
    'content': 'Calculate the average smart city technology adoption score of all cities in the database.'},
   {'role': 'assistant',
    'content': 'SELECT AVG(technology_adoption_score) FROM smart_cities;'}]},
 {'messages': [{'role': 'user',
    'content': 'List the top 3 destinations for US tourists interested in cultural tourism?'},
   {'role': 'assistant',
    'content': "SELECT destination, COUNT(*) as tourist_count FROM cultural_tourists WHERE nationality = 'USA' GROUP BY destination ORDER BY tourist_count DESC LIMIT 3;"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the total quantity of cotton sourced from the United States by brands that have committed to fair labor practices?'},
   {'role': 'assistant',
    'content': "SELECT SUM(quantity) FROM cotton_source WHERE country = 'USA' AND brand IN (SELECT brand FROM fair_labor WHERE commitment = 'yes');"}]},
 {'messages': [{'role': 'user',
    'content': "List all donations and the corresponding campaign from 'donations' and 'campaigns' tables"},
   {'role': 'assistant',
    'content': 'SELECT donations.donation_id, donations.donation_amount, donations.donation_date, campaigns.campaign_name FROM donations INNER JOIN campaigns ON donations.donation_date BETWEEN campaigns.start_date AND campaigns.end_date;'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average production of Europium per year?'},
   {'role': 'assistant',
    'content': "SELECT year, AVG(quantity) as avg_quantity FROM production_yearly WHERE element = 'Europium' GROUP BY year"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average number of public participation events per country in the American region?'},
   {'role': 'assistant',
    'content': "SELECT AVG(event_count) FROM participation WHERE region = 'American';"}]},
 {'messages': [{'role': 'user',
    'content': "What is the average amount of climate finance spent by 'medium' and 'large' organizations?"},
   {'role': 'assistant',
    'content': "SELECT AVG(amount) FROM org_climate_finance WHERE org_size IN ('medium', 'large');"}]},
 {'messages': [{'role': 'user', 'content': 'Create a view for female fans'},
   {'role': 'assistant',
    'content': "CREATE VIEW female_fans AS SELECT * FROM fans WHERE gender = 'Female';"}]},
 {'messages': [{'role': 'user',
    'content': "How many volunteers are registered in the 'Volunteers' table?"},
   {'role': 'assistant', 'content': 'SELECT COUNT(*) FROM Volunteers'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the total amount of transactions made by customers from India and Brazil?'},
   {'role': 'assistant',
    'content': "SELECT SUM(amount) FROM transactions WHERE country IN ('India', 'Brazil');"}]},
 {'messages': [{'role': 'user',
    'content': "Insert new eSports team records for the 'Genesis' organization"},
   {'role': 'assistant',
    'content': "INSERT INTO esports_teams (id, name, organization) VALUES (1, 'Genesis Titans', 'Genesis'), (2, 'Genesis Dragons', 'Genesis');"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average price of sustainable fabrics?'},
   {'role': 'assistant',
    'content': 'SELECT AVG(price) FROM sustainable_fabrics;'}]},
 {'messages': [{'role': 'user',
    'content': 'List the total number of workouts and unique members who participated in CrossFit classes in the last month.'},
   {'role': 'assistant',
    'content': "SELECT COUNT(DISTINCT id) as total_members, COUNT(*) as total_workouts FROM workouts WHERE workout_type = 'CrossFit' AND workout_date >= DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH);"}]},
 {'messages': [{'role': 'user',
    'content': "Update the 'contract_amount' field in the 'defense_contracts' table, increasing it by 10% for contracts awarded in Q2 2021"},
   {'role': 'assistant',
    'content': "UPDATE defense_contracts SET contract_amount = contract_amount * 1.1 WHERE award_date BETWEEN '2021-04-01' AND '2021-06-30';"}]},
 {'messages': [{'role': 'user',
    'content': "Delete all records related to the exhibition 'Temporary Closure' from the Exhibition_Visitors table."},
   {'role': 'assistant',
    'content': "DELETE FROM Exhibition_Visitors WHERE exhibition_id = (SELECT exhibition_id FROM Exhibitions WHERE exhibition_name = 'Temporary Closure');"}]},
 {'messages': [{'role': 'user',
    'content': 'List property co-owners in New York City who have not implemented accessibility features.'},
   {'role': 'assistant',
    'content': "SELECT CoOwners.CoOwnerID, Properties.City FROM CoOwners INNER JOIN Properties ON CoOwners.PropertyID = Properties.PropertyID WHERE Properties.City = 'New York City' AND Properties.Accessibility = 'No';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the name and state of the city with the highest population?'},
   {'role': 'assistant',
    'content': 'SELECT City.name, City.state FROM City ORDER BY City.population DESC LIMIT 1;'}]},
 {'messages': [{'role': 'user',
    'content': 'How many marine species are found in the Southern Ocean?'},
   {'role': 'assistant',
    'content': "SELECT COUNT(*) FROM marine_species WHERE location = 'Southern Ocean';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the sum of revenues for each vendor in a specific region?'},
   {'role': 'assistant',
    'content': 'SELECT vendors.region, SUM(sales.revenue) FROM vendors INNER JOIN sales ON vendors.vendor_id = sales.vendor_id GROUP BY vendors.region;'}]},
 {'messages': [{'role': 'user',
    'content': 'Showcase the types of traditional arts performed at each heritage site.'},
   {'role': 'assistant',
    'content': 'SELECT h.SiteName, a.ArtType FROM HeritageSites h JOIN ArtsHeritage a ON h.SiteName = a.SiteName;'}]},
 {'messages': [{'role': 'user',
    'content': "What is the earliest launch date for a satellite in the 'Satellites' table?"},
   {'role': 'assistant',
    'content': 'SELECT MIN(Launch_Date) FROM Satellites;'}]},
 {'messages': [{'role': 'user',
    'content': "Who are the top 3 artists with the highest number of art pieces in the 'Post-Impressionism' category?"},
   {'role': 'assistant',
    'content': "SELECT artist_name, num_pieces FROM (SELECT artist_name, category, num_pieces, RANK() OVER (PARTITION BY category ORDER BY num_pieces DESC) AS rank FROM Artist_Data) tmp WHERE rank <= 3 AND category = 'Post-Impressionism';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average time between the last inspection and the next scheduled inspection for each part type and manufacturer?'},
   {'role': 'assistant',
    'content': 'SELECT InspectionData.Type, InspectionData.Manufacturer, AVG(DATEDIFF(day, InspectionData.LastInspection, InspectionData.NextInspection)) as AvgTimeBetweenInspections FROM InspectionData GROUP BY InspectionData.Type, InspectionData.Manufacturer;'}]},
 {'messages': [{'role': 'user',
    'content': 'Identify brands that have increased their product count by more than 50% since last year.'},
   {'role': 'assistant',
    'content': 'SELECT brand_id, brand_name, ((products_this_year - products_last_year) * 100.0 / products_last_year) as growth_percentage FROM brands WHERE (products_this_year - products_last_year) > 0.5 * products_last_year ORDER BY growth_percentage DESC;'}]},
 {'messages': [{'role': 'user',
    'content': "What are the total costs of support programs from the 'SupportPrograms' table?"},
   {'role': 'assistant',
    'content': 'SELECT SUM(cost) FROM SupportPrograms;'}]},
 {'messages': [{'role': 'user',
    'content': 'Find states with more than 3 mental health parity laws.'},
   {'role': 'assistant',
    'content': "SELECT state, COUNT(*) as parity_law_count FROM mental_health_parity WHERE parity_law = 'yes' GROUP BY state HAVING COUNT(*) > 3;"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the maximum cargo weight for VesselC?'},
   {'role': 'assistant',
    'content': "SELECT max_cargo_weight FROM vessels WHERE name = 'VesselC';"}]},
 {'messages': [{'role': 'user',
    'content': "What is the maximum distance of all satellites from the Earth's surface, organized by country of origin?"},
   {'role': 'assistant',
    'content': 'SELECT country_of_origin, MAX(avg_distance) FROM satellites GROUP BY country_of_origin;'}]},
 {'messages': [{'role': 'user',
    'content': 'List the unique types of healthcare facilities in the rural healthcare system, excluding mobile clinics.'},
   {'role': 'assistant',
    'content': "SELECT DISTINCT Type FROM Hospitals WHERE Type != 'Mobile Clinic';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the daily ridership of public transportation in Toronto by mode?'},
   {'role': 'assistant',
    'content': "SELECT mode, SUM(ridership) FROM TOPublicTransportation WHERE date = '2022-03-01' GROUP BY mode;"}]},
 {'messages': [{'role': 'user',
    'content': 'List the machine IDs, types, and maintenance schedules for all machines in factories with unethical labor practices.'},
   {'role': 'assistant',
    'content': "SELECT machines.machine_id, machines.type, machines.schedule FROM machines INNER JOIN factories ON machines.factory_id = factories.factory_id WHERE factories.practices = 'unethical';"}]},
 {'messages': [{'role': 'user',
    'content': "What is the average delivery time for route 'R02'?"},
   {'role': 'assistant',
    'content': "SELECT AVG(delivery_time) FROM deliveries WHERE route_id = 'R02';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the total trade value and average price for each trader and stock in the trade_history table?'},
   {'role': 'assistant',
    'content': 'SELECT trader_id, stock, SUM(price * quantity) as total_trade_value, AVG(price) as avg_price FROM trade_history GROUP BY trader_id, stock;'}]},
 {'messages': [{'role': 'user',
    'content': "What are the total number of works in the 'Artworks' and 'Exhibitions' tables?"},
   {'role': 'assistant',
    'content': 'SELECT COUNT(*) FROM Artworks UNION ALL SELECT COUNT(*) FROM Exhibitions;'}]},
 {'messages': [{'role': 'user',
    'content': 'List the top 5 most popular sizes among customers'},
   {'role': 'assistant',
    'content': 'SELECT size, COUNT(*) as popularity FROM orders GROUP BY size ORDER BY popularity DESC LIMIT 5;'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the count of climate finance records for each sector in North America?'},
   {'role': 'assistant',
    'content': "SELECT sector, COUNT(*) FROM climate_finance WHERE location IN ('North America') GROUP BY sector;"}]},
 {'messages': [{'role': 'user',
    'content': 'List the space missions with the longest durations as of 2022.'},
   {'role': 'assistant',
    'content': "SELECT mission_name, TIMESTAMPDIFF(YEAR, start_date, COALESCE(end_date, CURDATE())) as 'Mission Duration (Years)' FROM SpaceMissions WHERE end_date IS NULL OR end_date >= '2022-01-01' ORDER BY 'Mission Duration (Years)' DESC"}]},
 {'messages': [{'role': 'user',
    'content': 'Update the description of a specific cybersecurity incident in the "cybersecurity_incidents" table'},
   {'role': 'assistant',
    'content': "UPDATE cybersecurity_incidents SET description = 'Unauthorized access to highly sensitive personal information' WHERE id = 1;"}]},
 {'messages': [{'role': 'user',
    'content': 'How many students with visual impairments have received accommodations in the last year?'},
   {'role': 'assistant',
    'content': "SELECT COUNT(*) FROM Accommodations INNER JOIN Students ON Accommodations.student = Students.id WHERE disability = 'visual impairment' AND date >= DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR);"}]},
 {'messages': [{'role': 'user',
    'content': 'Show the total funding amount for companies with female founders'},
   {'role': 'assistant',
    'content': "SELECT SUM(fr.funding_amount) FROM companies c INNER JOIN funding_rounds fr ON c.company_id = fr.company_id WHERE c.founder_gender = 'Female';"}]},
 {'messages': [{'role': 'user',
    'content': "What was the average fare collected on weekdays in February 2021 for the 'Red Line'?"},
   {'role': 'assistant',
    'content': 'SELECT AVG(fare) FROM red_line WHERE route_id = 102 AND EXTRACT(DAY FROM date) BETWEEN 2 AND 6 AND EXTRACT(MONTH FROM date) = 2;'}]},
 {'messages': [{'role': 'user',
    'content': 'List sustainable building practices with their descriptions'},
   {'role': 'assistant',
    'content': 'SELECT practice, description FROM sustainable_practices;'}]},
 {'messages': [{'role': 'user',
    'content': "Which sustainable practices were used in the 'Structural Engineering' department that cost over $10,000?"},
   {'role': 'assistant',
    'content': "SELECT SustainablePractices.PracticeName FROM SustainablePractices WHERE SustainablePractices.Department = 'Structural Engineering' AND SustainablePractices.Cost > 10000.00;"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average number of artworks in the collections from Oceania?'},
   {'role': 'assistant',
    'content': "SELECT AVG(artworks) FROM collections WHERE name LIKE '%Oceania%';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average account balance for customers in the Southeast region?'},
   {'role': 'assistant',
    'content': "SELECT AVG(account_balance) FROM customers WHERE region = 'Southeast';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average number of patients served per rural health center in Asia and how many of these centers serve more than 5000 patients?'},
   {'role': 'assistant',
    'content': "SELECT AVG(num_patients) AS avg_patients_per_center, COUNT(*) FILTER (WHERE num_patients > 5000) AS centers_with_more_than_5000_patients FROM rural_health_centers WHERE country IN (SELECT name FROM countries WHERE continent = 'Asia');"}]},
 {'messages': [{'role': 'user',
    'content': 'Who has the highest number of three-point field goals for the Celtics?'},
   {'role': 'assistant',
    'content': "SELECT home_team_three_point, away_team_three_point, (home_team_three_point + away_team_three_point) as total_three_point FROM games WHERE home_team_id = (SELECT team_id FROM teams WHERE team_name = 'Celtics') OR away_team_id = (SELECT team_id FROM teams WHERE team_name = 'Celtics') ORDER BY total_three_point DESC LIMIT 1;"}]},
 {'messages': [{'role': 'user',
    'content': "List all astronauts who had medical checkups in '2020' and their corresponding medical status."},
   {'role': 'assistant',
    'content': "SELECT name, medical_status FROM Astronauts WHERE medical_checkup_date >= '2020-01-01' AND medical_checkup_date < '2021-01-01';"}]},
 {'messages': [{'role': 'user',
    'content': 'Which suppliers provide raw materials to factories in the electronics industry?'},
   {'role': 'assistant',
    'content': "SELECT s.supplier_name FROM suppliers s INNER JOIN electronics_factories ef ON s.id = ef.supplier_id WHERE s.industry = 'Electronics';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average dissolved oxygen level for each location in the past 3 years?'},
   {'role': 'assistant',
    'content': 'SELECT location, AVG(dissolved_oxygen) as avg_dissolved_oxygen FROM dissolved_oxygen_readings WHERE year >= (SELECT MAX(year) - 3 FROM dissolved_oxygen_readings) GROUP BY location;'}]},
 {'messages': [{'role': 'user',
    'content': "What is the average number of attendees for events in the 'historical' category that have a price over 30?"},
   {'role': 'assistant',
    'content': "SELECT AVG(attendance) FROM events WHERE category = 'historical' AND price > 30;"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the total spending on humanitarian assistance by the European Union in the last 3 years?'},
   {'role': 'assistant',
    'content': 'SELECT SUM(spending) FROM defense.eu_humanitarian_assistance WHERE year BETWEEN 2019 AND 2021;'}]},
 {'messages': [{'role': 'user',
    'content': 'Show the number of biosensor technology patents filed in the USA and China, pivoted to display technology type as columns.'},
   {'role': 'assistant',
    'content': "SELECT country, SUM(CASE WHEN technology = 'Optical' THEN 1 ELSE 0 END) as optical, SUM(CASE WHEN technology = 'Electrochemical' THEN 1 ELSE 0 END) as electrochemical, SUM(CASE WHEN technology = 'Mass Spectrometry' THEN 1 ELSE 0 END) as mass_spectrometry FROM biosensors.patents WHERE country IN ('USA', 'China') GROUP BY country;"}]},
 {'messages': [{'role': 'user',
    'content': 'List all indigenous food systems in Europe that use permaculture farming methods.'},
   {'role': 'assistant',
    'content': "SELECT * FROM Indigenous_Food_Systems WHERE Country IN ('Spain', 'France') AND Farming_Method = 'Permaculture';"}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average depth of all marine protected areas in the world?'},
   {'role': 'assistant',
    'content': 'SELECT AVG(avg_depth) FROM marine_protected_areas;'}]},
 {'messages': [{'role': 'user',
    'content': 'What is the average price of artworks exhibited in the 20th century?'},
   {'role': 'assistant',
    'content': "SELECT AVG(Artworks.price) FROM Artworks INNER JOIN Exhibitions ON Artworks.artwork_id = Exhibitions.artwork_id WHERE Exhibitions.start_date BETWEEN '1900-01-01' AND '1999-12-31';"}]},

In [73]:
val_data[0]

{'messages': [{'role': 'user',
   'content': 'What is the minimum price of vegan skincare products sold in the United Kingdom?'},
  {'role': 'assistant',
   'content': "SELECT MIN(price) FROM SkincareProducts WHERE is_vegan = TRUE AND country = 'United Kingdom';"}]}

## Creating JSONL Files

In [74]:
import json

def write_to_jsonl(data, file_path):
    with open(file_path, 'w') as file:
        for entry in data:
            json.dump(entry, file)
            file.write('\n')

training_file_name = "train.jsonl"
validation_file_name = "val.jsonl"

write_to_jsonl(train_data, training_file_name)
write_to_jsonl(val_data, validation_file_name)

## Uploading Data and Starting the Fine-Tuning Job

In [75]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI()


# Upload Training and Validation Files
training_file = client.files.create(
    file=open(training_file_name, "rb"), purpose="fine-tune"
)
validation_file = client.files.create(
    file=open(validation_file_name, "rb"), purpose="fine-tune"
)

In [76]:
print("Training_id : ", training_file.id)
print("Validation id :", validation_file.id)

Training_id :  file-5rlIi2wCQNzMuzVur6FjMdpg
Validation id : file-sEdOw55HvHQzNpCePFrNRt9K

## Create Fine-Tuning Job

In [77]:
response = client.fine_tuning.jobs.create(
    training_file=training_file.id,
    validation_file=validation_file.id,
    model="gpt-3.5-turbo",
    suffix="text-to-sql",
)

In [78]:
response

FineTuningJob(id='ftjob-wL67oqMDw1ovE2frIyWK86CZ', created_at=1715435567, error=Error(code=None, message=None, param=None), fine_tuned_model=None, finished_at=None, hyperparameters=Hyperparameters(n_epochs='auto', batch_size='auto', learning_rate_multiplier='auto'), model='gpt-3.5-turbo-0125', object='fine_tuning.job', organization_id='org-jEJmvnn0sAe0ifDnYRWxdmRo', result_files=[], status='validating_files', trained_tokens=None, training_file='file-5rlIi2wCQNzMuzVur6FjMdpg', validation_file='file-sEdOw55HvHQzNpCePFrNRt9K', user_provided_suffix='text-to-sql', seed=645630885, estimated_finish=None, integrations=[])

In [90]:
response.id

'ftjob-wL67oqMDw1ovE2frIyWK86CZ'

In [98]:
client.fine_tuning.jobs.retrieve(response.id)

FineTuningJob(id='ftjob-wL67oqMDw1ovE2frIyWK86CZ', created_at=1715435567, error=Error(code=None, message=None, param=None), fine_tuned_model='ft:gpt-3.5-turbo-0125:personal:text-to-sql:9NiqfkTN', finished_at=1715440968, hyperparameters=Hyperparameters(n_epochs=3, batch_size=1, learning_rate_multiplier=2), model='gpt-3.5-turbo-0125', object='fine_tuning.job', organization_id='org-jEJmvnn0sAe0ifDnYRWxdmRo', result_files=['file-qTFxcOvRh7bMwMoxIrTp81Iv'], status='succeeded', trained_tokens=135678, training_file='file-5rlIi2wCQNzMuzVur6FjMdpg', validation_file='file-sEdOw55HvHQzNpCePFrNRt9K', user_provided_suffix='text-to-sql', seed=645630885, estimated_finish=None, integrations=[])

In [19]:
client.fine_tuning.jobs.list(limit=1)

SyncCursorPage[FineTuningJob](data=[FineTuningJob(id='ftjob-wL67oqMDw1ovE2frIyWK86CZ', created_at=1715435567, error=Error(code=None, message=None, param=None), fine_tuned_model='ft:gpt-3.5-turbo-0125:personal:text-to-sql:9NiqfkTN', finished_at=1715440968, hyperparameters=Hyperparameters(n_epochs=3, batch_size=1, learning_rate_multiplier=2), model='gpt-3.5-turbo-0125', object='fine_tuning.job', organization_id='org-jEJmvnn0sAe0ifDnYRWxdmRo', result_files=['file-qTFxcOvRh7bMwMoxIrTp81Iv'], status='succeeded', trained_tokens=135678, training_file='file-5rlIi2wCQNzMuzVur6FjMdpg', validation_file='file-sEdOw55HvHQzNpCePFrNRt9K', user_provided_suffix='text-to-sql', seed=645630885, estimated_finish=None, integrations=[])], object='list', has_more=True)

SyncCursorPage[FineTuningJob]
(data=[FineTuningJob(id='ftjob-wL67oqMDw1ovE2frIyWK86CZ',
created_at=1715435567, error=Error(code=None, message=None, param=None),
fine_tuned_model='ft:gpt-3.5-turbo-0125:personal:text-to-sql:9NiqfkTN', 
finished_at=1715440968, 

hyperparameters=Hyperparameters(n_epochs=3, batch_size=1, learning_rate_multiplier=2), 

model='gpt-3.5-turbo-0125', object='fine_tuning.job', organization_id='org-jEJmvnn0sAe0ifDnYRWxdmRo', 
result_files=['file-qTFxcOvRh7bMwMoxIrTp81Iv'], 
status='succeeded', trained_tokens=135678, training_file='file-5rlIi2wCQNzMuzVur6FjMdpg', validation_file='file-sEdOw55HvHQzNpCePFrNRt9K', 
user_provided_suffix='text-to-sql', seed=645630885, estimated_finish=None, integrations=[])], object='list', has_more=True)

### TEST FINETUNED MODEL

### id : ft:gpt-3.5-turbo-0125:personal:text-to-sql:9NiqfkTN

In [1]:
from openai import OpenAI
from dotenv import load_dotenv
from datasets import load_dataset
import pandas as pd
import os

/home/yasser/Documents/pa/.pa/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = load_dataset("gretelai/synthetic_text_to_sql", split='train')
df = df.to_pandas()

In [23]:
df.head(5)

,id,domain,domain_description,sql_complexity,sql_complexity_description,sql_task_type,sql_task_type_description,sql_prompt,sql_context,sql,sql_explanation
0,5097,forestry,Comprehensive data on sustainable forest manag...,single join,"only one join (specify inner, outer, cross)",analytics and reporting,"generating reports, dashboards, and analytical...",What is the total volume of timber sold by eac...,"CREATE TABLE salesperson (salesperson_id INT, ...","SELECT salesperson_id, name, SUM(volume) as to...","Joins timber_sales and salesperson tables, gro..."
1,5098,defense industry,"Defense contract data, military equipment main...",aggregation,"aggregation functions (COUNT, SUM, AVG, MIN, M...",analytics and reporting,"generating reports, dashboards, and analytical...",List all the unique equipment types and their ...,CREATE TABLE equipment_maintenance (equipment_...,"SELECT equipment_type, SUM(maintenance_frequen...",This query groups the equipment_maintenance ta...
2,5099,marine biology,"Comprehensive data on marine species, oceanogr...",basic SQL,basic SQL with a simple select statement,analytics and reporting,"generating reports, dashboards, and analytical...",How many marine species are found in the South...,"CREATE TABLE marine_species (name VARCHAR(50),...",SELECT COUNT(*) FROM marine_species WHERE loca...,This query counts the number of marine species...
3,5100,financial services,Detailed financial data including investment s...,aggregation,"aggregation functions (COUNT, SUM, AVG, MIN, M...",analytics and reporting,"generating reports, dashboards, and analytical...",What is the total trade value and average pric...,"CREATE TABLE trade_history (id INT, trader_id ...","SELECT trader_id, stock, SUM(price * quantity)...",This query calculates the total trade value an...
4,5101,energy,Energy market data covering renewable energy s...,window functions,"window functions (e.g., ROW_NUMBER, LEAD, LAG,...",analytics and reporting,"generating reports, dashboards, and analytical...",Find the energy efficiency upgrades with the h...,"CREATE TABLE upgrades (id INT, cost FLOAT, typ...","SELECT type, cost FROM (SELECT type, cost, ROW...",The SQL query uses the ROW_NUMBER function to ...

In [10]:
load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

In [11]:
print(f"API Key: {api_key}")

API Key: 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

In [27]:
df[df['id'] == 5099]['sql_prompt'][2]

'How many marine species are found in the Southern Ocean?'

In [28]:
client = OpenAI()

completion = client.chat.completions.create(
  model="ft:gpt-3.5-turbo-0125:personal:text-to-sql:9NiqfkTN",
  messages=[
    {"role": "user", 
     "content": "How many marine species are found in the Southern Ocean?"
     }
  ]
)

In [29]:
print(completion.choices[0].message.content)

SELECT COUNT(*) FROM marine_species WHERE location = 'Southern Ocean';

In [30]:
df[df['id'] == 5099]['sql'][2]

"SELECT COUNT(*) FROM marine_species WHERE location = 'Southern Ocean';"